name: vaden_workspace
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - vaden
  - vaden/example
  - vaden_class_scanner
  - packages/anaki_orm

dependencies:
  args: ^2.6.0
  vaden: any

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  vaden: bin/vaden.dart
